name: Generate SBOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate SBOM with cdxgen
        run: |
          npm install -g @cyclonedx/cdxgen
          cdxgen -t maven -o sbom.cyclonedx.json .

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-file
          path: ./sbom.cyclonedx.json
          retention-days: 30

  import-sbom-deptrack:
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
        - name: Download SBOM artifact
          uses: actions/download-artifact@v4
          with:
            name: sbom-file

        - name: Import SBOM to Dependency Track using CURL
          run: |
            # Base64 encode the SBOM file
            SBOM_BASE64=$(base64 -w0 sbom.cyclonedx.json)
            
            # Create JSON payload
            cat > payload.json << EOF
            {
              "project": "Dependency-Track-PoC",
              "version": "v1",
              "autoCreate": true,
              "bom": "$SBOM_BASE64"
            }
            EOF
            
            # Send the request to Dependency Track
            curl -X PUT "https://dtrack-development.stpst.nl/api/v1/bom" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ secrets.DEPTRACK_APIKEY }}" \
              -d @payload.json
          env:
            CURL_VERBOSE: "true"